#!/bin/bash
IS_GLOBAL=0
BASE=${BASH_SOURCE[0]}
PARENT_DIR="$(dirname "$(dirname "$0")")"

set -o allexport
if [[ $BASE == "./console" ]]
then
    SOURCE="."
    source .env
else 
    IS_GLOBAL=1
    source ${BASE%"/bin/%APP_NAME%"}/.env 
    SOURCE=${BASE%"/bin/$APP_NAME"}
    source $SOURCE/bin/autocomp.sh
fi

# IMPORTS
source $SOURCE/docker/env/.env.$ENV
source $SOURCE/scripts/install.sh
source $SOURCE/scripts/misc/colors.sh
source $SOURCE/scripts/functions/base.sh
source $SOURCE/scripts/select.sh

set +o allexport